
[site]
url = "/knowledge"
name = "tcptty"
description = ""

menu = [
    { name = "About", url = "/about" },
    { name = "Blog", url = "/" },
]

[authors]
tcptty = {}

[theme]
background_image = "/static/bg.jpg"